"""add college table

Revision ID: c975a46efb23
Revises: 1c3484b1939f
Create Date: 2019-02-24 16:04:59.911661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c975a46efb23'
down_revision = '1c3484b1939f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('college',
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('unitid', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('address1', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=50), nullable=True),
    sa.Column('state', sa.String(length=5), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('web_url', sa.String(length=300), nullable=True),
    sa.Column('admissions_url', sa.String(length=300), nullable=True),
    sa.Column('application_url', sa.String(length=300), nullable=True),
    sa.Column('netprice_url', sa.String(length=300), nullable=True),
    sa.Column('sector', sa.String(length=3), nullable=True),
    sa.Column('hbcu', sa.String(length=3), nullable=True),
    sa.Column('locale', sa.String(length=3), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('unitid')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('college')
    # ### end Alembic commands ###
